### ISSUE TITLE
Does this project support for ros noetic and ubuntu 20.04?

### ISSUE THREAD

**Issue by JACKLiuDay** [Cc19245/LVI-SAM-Easyused#1]
Hi, thank you for sharing your LVI project. I wonder to know if this project support for ros noetic and ubuntu 20.04?

**Comment by Cc19245** [comment]
> Hi, thank you for sharing your LVI project. I wonder to know if this project support for ros noetic and ubuntu 20.04?

Hi, this project has exactly the same dependencies as the original [LVI-SAM](https://github.com/TixiaoShan/LVI-SAM). I think it can run on ubuntu 20.04 , but I haven't tested it.

**Comment by JACKLiuDay** [comment]
> > Hi, thank you for sharing your LVI project. I wonder to know if this project support for ros noetic and ubuntu 20.04?
> 
> Hi, this project has exactly the same dependencies as the original [LVI-SAM](https://github.com/TixiaoShan/LVI-SAM). I think it can run on ubuntu 20.04 , but I haven't tested it.

Hi, thank you for your quick reply. I will try it and tell you the test result.
