### ISSUE TITLE
关于KITTI数据集的问题

### ISSUE THREAD

**Issue by 504115681** [Cc19245/LVI-SAM-Easyused#10]
大佬，我跑KITTI数据集的序列00，在150s左右轨迹会原地不动，很奇怪，我把VIO关了只跑LIO，也是这样。但是，我下载LIO-SAM测试，就没这个问题，想问问你知道是什么问题嘛？非常感谢！

**Comment by keeper-w** [comment]
你好，我也遇到了类似的问题，请问你是怎么解决的呢？
